// Code generated by MockGen. DO NOT EDIT.
// Source: router.go
//
// Generated by this command:
//
//	mockgen -source=router.go -destination=mock.go -package=routers
//

// Package routers is a generated GoMock package.
package routers
